# Generated by Django 4.1.7 on 2023-03-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('genres', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('language', models.CharField(default='malayalam', max_length=200)),
                ('rating', models.FloatField(max_length=200)),
            ],
        ),
    ]
